### ISSUE TITLE
Please Add answer of last two questions of Sprint 2

### ISSUE THREAD

**Issue by thakurbrajeshsingh** [taylorswift58037/Capgemini-ADAPT-Stage1#1]

**Comment by taylorswift58037** [comment]
Check now I have updated them I think

**Comment by thakurbrajeshsingh** [comment]
Bro i am not able to find the sprint 2 codes of toy rental .can pls. comment exact link for the codes

**Comment by taylorswift58037** [comment]
For help join my telegram channel https://t.me/code_4_fun

**Comment by pallavirai8085** [comment]
![IMG-20220819-WA0032](https://user-images.githubusercontent.com/111571220/185604680-12e3aec3-008a-4d34-b453-70e4e2288be4.jpg)
![IMG-20220819-WA0031](https://user-images.githubusercontent.com/111571220/185604686-b0664387-dc8c-4ee3-8ed8-781fd5f29dd5.jpg)
![IMG-20220819-WA0034](https://user-images.githubusercontent.com/111571220/185604688-dd1ac8c1-b428-4e2e-9f89-a7528e72c088.jpg)
![IMG-20220819-WA0033](https://user-images.githubusercontent.com/111571220/185604691-bd280950-a6c3-40ee-ae00-7d449f506795.jpg)
Help

**Comment by taylorswift58037** [comment]
Contact me in telegram @Code_4_Fun_Owner
